### PR TITLE
Feature/urllib python2 and 3

### PR DESCRIPTION
**Pull request by rolando-ebi**

### CODE REVIEW

**Comment by simonjupp** [comment]
@rolando-ebi I know this was a pretty old PR. I was trying to see if I could bring it up to date and merge . The tests are not passing for python 2 so I won't merge. Do we need this?

**Comment by simonjupp** [comment]
@rolando-ebi I know this was a pretty old PR. I was trying to see if I could bring it up to date and merge . The tests are not passing for python 2 so I won't merge. Do we need this?

**Comment by simonjupp** [comment]
@rolando-ebi I know this was a pretty old PR. I was trying to see if I could bring it up to date and merge . The tests are not passing for python 2 so I won't merge. Do we need this?

**Comment by rolando-ebi** [comment]
I dont think we need this branch, pretty outdated at this stage

**Pull request closed without merging**
