### PR TITLE
Added back the dry_run_import_file method to return entity map which contains linking info

### PR DESCRIPTION
**Pull request by aaclan-ebi**

### CODE REVIEW

**Comment by javfg** [comment]
This was being used by the work in progress code in HumanCellAtlas/ingest-graph-validator. Not sure if there is a way to avoid using it in the future yet, but if there is, I will notify so it is removed again.

**Comment by aaclan-ebi** [comment]
Regarding @ESapenaVentura 's question, “what’s the cost of providing that method?” (good question!) If ever we need to refactor the entity map obj, that will prevent us to do so. It would be nice to expose only the info needed for the graph validator.

**Comment by javfg** [comment]
I should be able to remove it from the script as soon as I know what it does and how to do it without using the function.

**Comment by aaclan-ebi** [comment]
Yes, no worries! we can retain the function but we could probably change the output obj/format.

**Pull request merged**
